version: '3'

services:
  digapp_auth_ms:
    container_name: digapp_auth_ms
    restart: always
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - digapp_auth_db
  
  digapp_auth_db:
    container_name: digapp_auth_db
    image: mongo
    ports:
      - "27017:27017"