version: '3'

services:
  digapp_usermanagment_ms:
    container_name: digapp_usermanagment_ms
    restart: always
    build: .
    ports: 
      - "4000:3000"
    links:
      - digapp_usermanagment_db
  
  digapp_usermanagment_db:
    container_name: digapp_usermanagment_db
    image: mongo
    ports:
      - "27017:27017"